### PR TITLE
[summary] add API to allow overriding job type word forms

### LINKED ISSUE #35: Would like verbs to be able to override what the jobs are called in SummaryHandler
I have an experimental verb which operates at the repo- rather than package level. It's working great, but it's too bad that the summary at the end of a run still refers to `n packages finished`, in this code (and elsewhere):

https://github.com/colcon/colcon-output/blob/a220a1cd27ec850e025a10224ca4c542c9fa7817/colcon_output/event_handler/summary.py#L74-L77

Not sure how much visibility this code and the running verb have into each other, but it would be nice if the `SummaryHandler` could somehow be passed a `singular/plural` tuple of what to refer to the jobs as.

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #35.

### CODE REVIEW

**Comment by mikepurvis** [comment]
This looks like it will work for me, thanks! Are you picturing that the verb plugin would monkey-patch this at import time, or is there a more structured way for me to get access to the SummaryHandler? Currently my code doesn't see this class at all, as it just blindly throws a big job dict at `colcon_core.executor.execute_jobs`.

**Comment by dirk-thomas** [comment]
> or is there a more structured way for me to get access to the SummaryHandler?

Those different code parts are so "far" from each other with no shared interface I don't see a better structured way to make this access more explicit.

> Are you picturing that the verb plugin would monkey-patch this at import time

Yes, that was what I was thinking.

**Comment by dirk-thomas** [comment]
> or is there a more structured way for me to get access to the SummaryHandler?

Those different code parts are so "far" from each other with no shared interface I don't see a better structured way to make this access more explicit.

> Are you picturing that the verb plugin would monkey-patch this at import time

Yes, that was what I was thinking. Actually probably not at import time but at runtime of that custom verb before starting to execute jobs.

**Comment by mikepurvis** [comment]
Okay, sounds good. I wondered if it might be possible to somehow synthesize an event that the SummaryHandler would receive to set this terminology, but I don't feel I have enough of a handle on how that whole part of the framework functions.

**Comment by dirk-thomas** [comment]
> I wondered if it might be possible to somehow synthesize an event that the SummaryHandler would receive to set this terminology

That would be possible too.

**Comment by dirk-thomas** [comment]
> I wondered if it might be possible to somehow synthesize an event that the SummaryHandler would receive to set this terminology

That would be possible too. At least if you do have access to the event queue. Not sure that is the case in all possible scenarios...

**Comment by mikepurvis** [comment]
I think what you have here is fine for now; if more use-cases emerge where people want to use the executor for non-package jobs, it can be revisited. The only one I can think of at the moment might be something related to parallelizing tests at a sub-package granularity, but I did play with that a bit in a previous catkin_tools plugin and it turned out be hairier than I expected; was not at all clear that the complexity was worth it.

**Pull request merged**
